examples/fashionmnist_autoencoder.exs
=> FashionMNIST dataset and basic autoencoder

lib/axon.ex, lib/axon/compiler.ex, lib/axon/parameter.ex, mix.lock, test/axon_test.exs
=> Add frozen layer mechanism

lib/axon.ex, lib/axon/compiler.ex, lib/axon/recurrent.ex, test/axon_test.exs, test/compiler_test.exs, test/mixed_precision_test.exs
=> Add use_bias option

lib/axon/compiler.ex, lib/axon/shape.ex, test/compiler_test.exs
=> Validate input shapes

lib/axon.ex, lib/axon/compiler.ex, lib/axon/shape.ex, test/axon_test.exs, test/compiler_test.exs
=> Handle constants in shape layers

lib/axon/compiler.ex
=> Fix compilation cache

lib/axon/compiler.ex, test/compiler_test.exs
=> Handle constant only networks

README.md
Since Sean generated the API documentation I thought it would be useful for the community to find it via the README.md as well.
=> Add API documentation to README.md

.github/workflows/test.yaml, lib/axon/loop.ex
=> Explicitly checkout axon in axon_onnx job

.formatter.exs, lib/axon.ex, lib/axon/compiler.ex, lib/axon/layers.ex, lib/axon/loop.ex, lib/axon/updates.ex, test/compiler_test.exs, test/loop_test.exs
=> Track mean and variance in batch norm

lib/axon.ex, lib/axon/compiler.ex, test/axon_test.exs, test/compiler_test.exs
=> Lazily generate model names

lib/axon.ex, lib/axon/layers.ex, lib/axon/shape.ex
=> Support dilations in pool

lib/axon/compiler.ex, notebooks/fashionmnist_autoencoder.livemd, notebooks/multi_input_example.livemd
I rewrote two of the examples from Axon into livebooks.
=> New notebooks 

.gitignore, examples/vision/horses_or_humans.exs, examples/vision/mnist.exs, lib/axon/loop.ex, test/loop_test.exs
=> Improve horses or humans

lib/axon.ex, mix.lock
Resolves #26 
Trying to find a better way to test
Note that #205 is more related to the Loop API and serializing training state. Similar to how in PyTorch you can save an entire state dict to resume training.
=> Initial draft of model serialization

lib/axon/loop.ex, lib/axon/loop/state.ex, test/loop_test.exs
This is a draft of loop checkpoints.
This resolves #205 and should be sufficient to outline a resolution for #201.
It also addresses model checkpoint handler in #142.
=> First draft of loop checkpoints

lib/axon/loop.ex
WIP
Resolves #142 
Needs tests and ability to stop on thresholds
=> Add early stopping

lib/axon/layers.ex, lib/axon/shape.ex, test/layers_test.exs
=> Fix channels last problem

lib/axon/layers.ex
=> Cubic resample

lib/axon.ex, lib/axon/compiler.ex, lib/axon/shared.ex, test/axon/compiler_test.exs, test/axon/loop_test.exs, test/axon_test.exs
Resolves #219 
I ended up refactoring the compiler a lot because I realized how I was doing things before was wrong, so it's much cleaner now IMO
=> Add Axon.container

lib/axon.ex, lib/axon/compiler.ex, lib/axon/initializers.ex, lib/axon/layers.ex, lib/axon/losses.ex, lib/axon/metrics.ex, lib/axon/shared.ex, test/axon/initializers_test.exs, test/axon/layers_test.exs, test/axon/losses_test.exs
Resolves #65 
My goal here is to try and raise with a clear error in Axon before reaching `Nx` because with complex networks the `Nx` stacktraces can be overwhelming to debug
=> Add shape assertions

lib/axon/updates.ex, test/axon/updates_test.exs
Resolves #222 
While the cases are more verbose I think it makes the API much friendlier
=> Make options optional in updates

lib/axon.ex, lib/axon/compiler.ex, lib/axon/layers.ex, lib/axon/shape.ex, test/axon/compiler_test.exs, test/axon/mixed_precision_test.exs, test/axon_test.exs
WIP
Trying to condense compiler cases down as much as possible. Having had to add stuff to the compiler way too many times, it's really annoying to have to repeat the same process for a bunch of clauses, so the goal here is to unify as much logic as possible.
=> Start to condense some compiler cases

lib/axon.ex, test/axon/compiler_test.exs
=> Standardize layer names on binaries

lib/axon.ex, lib/axon/compiler.ex, lib/axon/initializers.ex, lib/axon/shared.ex, test/axon/compiler_test.exs, test/axon/initializers_test.exs, test/axon/updates_test.exs, test/axon_test.exs, test/test_helper.exs
This enables configurable/custom initializers in Axon layers, which is a requirement for some other projects :)
=> Update Initializers API

lib/axon.ex, test/axon/compiler_test.exs, test/axon/loop_test.exs, test/axon/mixed_precision_test.exs, test/axon_test.exs
=> Fix containers

README.md, examples/basics/multi_input_example.exs, examples/basics/multi_output_example.exs, examples/generative/fashionmnist_autoencoder.exs, examples/generative/mnist_gan.exs, examples/structured/credit_card_fraud.exs, examples/vision/cifar10.exs, examples/vision/cnn_image_denoising.exs, examples/vision/horses_or_humans.exs, examples/vision/mnist.exs, examples/vision/resnet50.exs, notebooks/fashionmnist_autoencoder.livemd, notebooks/mnist.livemd, notebooks/multi_input_example.livemd
Hey :wave: 
According to [this](https://github.com/elixir-nx/axon/pull/239#issuecomment-1118470841) I have been trying to make the examples for axon to work and this is the resulting PR.
All of the examples seem to be working now. But It would be nice if someone else would test and confirm.
=> Update and fix examples

lib/axon.ex, lib/axon/compiler.ex, test/axon/compiler_test.exs, test/axon_test.exs
=> Support optional inputs

lib/axon.ex, lib/axon/compiler.ex, lib/axon/shape.ex, lib/axon/shared.ex, test/axon/compiler_test.exs
=> Allow containers as inputs

lib/axon/compiler.ex, test/axon/compiler_test.exs
=> Raise better error on missing parameters

lib/axon.ex, lib/axon/compiler.ex, test/axon/compiler_test.exs
=> Add debug utilities to Axon

examples/generative/text_generator.exs, notebooks/text_generator.livemd
This example is based on [this post](https://machinelearningmastery.com/text-generation-lstm-recurrent-neural-networks-python-keras/) by Jason Brownlee.
=> Add LSTM text generator example and livebook

lib/axon.ex
Resolves #316 
We freeze names and then rebuild the function to avoid trying to serialize functions. Custom layers will still present an issue, but I think fixing that might require a different solution
=> Freeze names in serialization

lib/axon/loop.ex
Minor changes to update `Loop.evaluator` example in the docs so it is consistent with the actual function.
Fixes #328
=> Update Loop.evaluator doc

lib/axon.ex, lib/axon/layers.ex, test/axon/compiler_test.exs, test/axon/layers_test.exs
Takes implementation from the other library. The implementation only supports 2-d spatial inputs, but I think that's okay for now :)
Resolves #320
=> Uses working resize

lib/axon/loop.ex
=> Add debug option to Loop

lib/axon.ex, test/axon_test.exs
=> Improve inspection

lib/axon/loop.ex, lib/axon/optimizers.ex, lib/axon/updates.ex, test/axon/updates_test.exs
Resolves #217 
Adds a stateful scale which can be adjusted by the Loop API.
=> Add stateful learning rate

lib/axon.ex, lib/axon/layers.ex, lib/axon/recurrent.ex, test/axon/compiler_test.exs, test/axon_test.exs
=> Update RNN formats

notebooks/humans_or_horses.livemd
Added a really simple Exploratory Analysis section and
configuration module.
All hanging functions were put inside modules.  The livebook
can run to completion on my CPU.
=> Updated the humans_or_horses livebook

lib/axon/losses.ex, test/axon/losses_test.exs
=> cosine_similarity

notebooks/README.md, notebooks/onnx_to_axon.livemd
@meanderingstream, can you please take a look if everything still makes sense from your side? Thank you!
=> Update Axon to Onnx to latest Livebook and simplify snippets

test/axon/activations_test.exs, test/axon/compiler_test.exs, test/axon/layers_test.exs, test/axon/loop_test.exs, test/axon/losses_test.exs, test/axon/optimizers_test.exs, test/test_helper.exs
the goal here is to categorize torchx tests so we can more easily tackle same-type bugs
=> chore: categorize torchx tests

.vscode/settings.json, lib/axon.ex, lib/axon/activations.ex, lib/axon/layers.ex, test/axon_test.exs
=> log_sumexp initial implementation

lib/axon.ex
=> docs: update lstm return type

lib/axon/display.ex
Can be verified with `mix compile --force --no-optional-deps`.
=> Fix compilation warnings without optional dependencies

lib/axon/display.ex
Currently a lonely input is not shown in the visualization, but it is actually useful:
Separating nodes and edges also has the advantages of reducing the graph text size if the same node has multiple edges.
I changed inputs to use a distinctive parallelogram (it seems that's used for inputs in flowcharts):
=> Show inputs without edges in the graph visualization

lib/axon/compiler.ex, test/axon/compiler_test.exs
This code:
input = Axon.input("input")
x1 = Axon.dense(input, 32)
x2 = Axon.dense(input, 64)
model = Axon.add(x1, x2)
{init_fn, _predict_fn} = Axon.build(model)
init_fn.(Nx.template({1, 16}, :f32), %{})
Now emits the following stacktrace:
** (ArgumentError) cannot broadcast tensor of dimensions {1, 32} to {1, 64}
(nx 0.3.0) lib/nx/shape.ex:335: Nx.Shape.binary_broadcast/4
(nx 0.3.0) lib/nx.ex:3513: Nx.element_wise_bin_op/4
(elixir 1.15.0-dev) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
(axon 0.2.0) expanding Axon layer add_0: Axon.Layers.add/2
(axon 0.2.0) lib/axon/compiler.ex:58: anonymous fn/3 in Axon.Compiler.build/2
(stdlib 4.0) timer.erl:235: :timer.tc/1
Notice we also added stacktrace pruning. Therefore, when debugging Axon.Compiler itself, it may be desired to temporarily …
=> Include layer name in stacktraces

notebooks/generative/fashionmnist_vae.livemd
This is still a work in progress, I haven't gotten to the variational part yet.
But I'm finding that the training on Fashion MNIST results in getting `:nan` parameters after ~10-15 epochs. I *think* this is due to exploding gradients, but I'm not sure how to debug it or apply gradient clipping in Axon.
=> Add an example notebook for a variational autoencoder

.github/workflows/gh-pages.yml, .github/workflows/test.yaml
I noticed we are missing caching, so I did some improvements. Will re-run to verify
=> Improve CI

lib/axon.ex, lib/axon/layers.ex, mix.lock, test/axon/initializers_test.exs
* Remove some deprecation warnings
* Rewrite rnn to rely less on deprecated transform
=> Update to latest Nx

lib/axon.ex, lib/axon/layers.ex, test/axon_test.exs
Resolves #323 
For now, just warns. Will raise on next release
=> Warn on non-MFA functions

lib/axon/loop.ex, lib/axon/loss_scale.ex, mix.exs, test/axon/loop_test.exs
=> Adds loss scaling to Axon

lib/axon/loop.ex
=> Add gradient accumulation

lib/axon/compiler.ex, lib/axon/updates.ex, test/axon/compiler_test.exs
Resolves #408 
The issue is that namespaced models with stateful layers were not updated correctly
=> Fix issue with namespaced stateful models

lib/axon/schedules.ex, test/axon/optimizers_test.exs, test/axon/schedules_test.exs, test/axon/updates_test.exs
=> Update schedules to require initial value

lib/axon/loop.ex, test/axon/integration_test.exs, test/axon/loop_test.exs
Forwards keys to training.
We need to consider other sources of non-determinism too, such as dropout and how fixes for #423 might affect this test
=> Make training deterministic

lib/axon/loop.ex
This may solve #416.
Please check @seanmor5. :)
=> Build evaluator and zero metrics only once

lib/axon/layers.ex, lib/axon/shape.ex, test/axon/layers_test.exs
=> Fix conv transpose with channels last

lib/axon/shared.ex, lib/axon/updates.ex, mix.exs, test/axon/integration_test.exs
=> Fix mismatch for certain optimizers with dropout

lib/axon/losses.ex
=> Add huber loss

lib/axon.ex, lib/axon/layers.ex, lib/axon/losses.ex, test/axon/compiler_test.exs, test/axon/loop_test.exs, test/axon/losses_test.exs
These are some regularization techniques proven to significantly feed up training by Mosaic. My plan is to integrate some or all of the Mosaic algorithms. These are 2 simple ones used in ResNet training
=> Add some features from Mosaic ML

examples/basics/multi_output_example.exs, examples/vision/cifar10.exs
Hi, 
Minor changes to the examples.
Thanks for your hard work on this library!
=> Fixes a few warnings in the example scripts

notebooks/generative/fashionmnist_autoencoder.livemd
=> Fix typo in fashionmnist_autoencoder.livemd

lib/axon.ex
Fix: https://github.com/elixir-nx/axon/issues/518
=> make attach_hook API compatible with Axon.Node and fix doc example on Axon.map_nodes

lib/axon/loop.ex
Fix: https://github.com/elixir-nx/axon/issues/523
On 58 iterations, before this PR:
with the updated code:
=> Iteration bug multiple plots

lib/axon/losses.ex
=> Fix typos in docs about options

notebooks/time_series/apple_stock_prices.livemd
Adds simple notebook showcasing an example of time-series regression using RNN.
=> Add time-series regression example notebook
