elixir-nx/axon

examples/xor.exs
lib/axon.ex
lib/axon/compiler.ex
test/axon_test.exs

Resolves #35 WIP, but this is how custom layers will look, specifically look at the xor example for the worst custom layer implementation of all time using `atan2` and a trainable weight. I will clean this up and fix the tests before this can be merged.

Initial custom layer implementation

---

lib/axon/layers.ex
lib/axon/training.ex

Per discussion in #25, changes here adapt the training API to accept `inputs` and `labels` that are streams.

Training API uses streams

---

lib/axon/initializers.ex
test/initializers_test.exs

This PR aims to add `Axon.Initializers.orthogonal/1` for #1
From what I read in https://www.tensorflow.org/api_docs/python/tf/keras/initializers/Orthogonal, we can implement this through Nx.LinAlg.qr + Nx.reshape in some combination.
@seanmor5 is this the right path? I've only added this base case as a proof of concept

feat: add orthogonal initializer

---

lib/axon.ex

The inspect module expects the operation to be an atom but in LSTM model has some operation as a function.

fix inspect of operation

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/initializers.ex
lib/axon/layers.ex
lib/axon/recurrent.ex
lib/axon/shape.ex
test/axon_test.exs
test/compiler_test.exs
test/mixed_precision_test.exs

The purpose of this is to add some basic tests of compilation of each layer before building up more complex integration tests. The focus is mainly to make sure that initialization and forward pass, as well as more complex things like model freezing and parameter policies work as expected. I'm pretty much testing models exactly against their implementation in `Axon.Layer` as the implementations should be tested individually in the layer test.

Add compiler test

---

examples/fashionmnist_autoencoder.exs

Issue:
(ArgumentError) invalid input shape given to model, expected input with shape {nil, 1, 28, 28}, but got input with shape {1, 28, 28}

Fix: sample image shape

---

examples/cifar10.exs

Issue:
(ArgumentError) cannot reshape, current shape {3, 3, 32, 32} is not compatible with new shape {3, 28, 28}

Fix: test images tesor shape

---

.github/workflows/test.yaml

This checks out the Axon Onnx repository and runs the tests using the current branch as the Axon dependency. This will provide immediate feedback if an update in Axon breaks something in the AxonOnnx project.

Add Axon ONNX workflow to CI/CD

---

lib/axon.ex
lib/axon/shape.ex
test/axon_test.exs
test/compiler_test.exs

This is to match Nx and to make it easy to implement these layers in ONNX because ONNX has different broadcasting semantics than ours.

Update broadcasting semantics in element-wise operations

---

lib/axon/loop.ex

In exisiting implementation value `state.max_iteration` is different depending on the epoch number. Precisely, it is equal to `initial_max_iteration + epoch_index` because after each epoch variable `state.iteration` accepts value of the corresponding `state.max_iteration` incremented by 1. Probably there is a problem in some internal loop over training batches, but solution proposed in this pull request seems simple and effective.

Fixed max_iteration parameter updates in the loop module

---

lib/axon/loop.ex
test/loop_test.exs

This change allows to take values which remain unchanged in comparison to the result of the previous iteration and pass them to the next iteration. It can be useful in cases, when custom loop handlers keep some data in training state (for instance, minimum or maximum loss).

Allow user-defined values in the `step_state` to propagate across iterations

---

examples/vision/horses_or_humans.exs
lib/axon/updates.ex

Adapted from: https://keras.io/examples/vision/gradient_centralization/
We actually can very easily implement Gradient Centralization with a minor addition to the optimization API. I'm planning that for tomorrow and will update this example accordingly.
I used Flow just to see how easily it could integrate with the API. I'm not even sure if it's a good or bad :)
This example should eventually be updated to make use of whatever Computer Vision solution we come up with. For now I used the `pixel` library which was the first one I found for decoding PNGs to binaries. In the future, it'd be ideal to combine this functionality with a library that also includes augmentations and manipulations on image tensors.

Add horses or humans example

---

examples/generative/fashionmnist_autoencoder.exs
examples/generative/mnist_gan.exs
examples/structured/credit_card_fraud.exs
examples/vision/cifar10.exs
examples/vision/cnn_image_denoising.exs
examples/vision/mnist.exs

Scidata `download/0` API [has changed slightly](https://github.com/elixir-nx/scidata/pull/18) and no longer accepts transform callbacks, so we can apply transformations to inputs and outputs after downloading.

Update Scidata version and callbacks examples

---

lib/axon/loop.ex
test/loop_test.exs

WIP to add a validation API to Axon loops. Validation sets are used as a "holdout" set to monitor and prevent overfitting. There are a few unresolved issues as of now:
1) How do we or do we even need to forward the outer loops compilation options to this inner loop?
2) Should we forward the model as well so it does not need to be explicitly specified? This would require adding some sort of `metadata` field to loop state.
3) How do we initialize state such that we are not changing the form of it and recompiling our train step after the first epoch because state now includes additional fields? I think this would probably go somewhat along with 1 and some sort of metadata field.
I'm also exploring different forms of this function to offer maximum control over the process. Overall though I …

Add validation handler

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/layers.ex
lib/axon/shape.ex
test/compiler_test.exs

Proof-of-concept of basic upsampling layer using bilinear interpolation. Requires https://github.com/elixir-nx/nx/issues/419 to be fixed. Needs to be tested on EXLA. The current `slice_grid` implementation might result in issues because it generates a large expression with a bunch of slices.

Add resize layer

---

examples/generative/mnist_gan.exs
examples/structured/credit_card_fraud.exs
examples/xor.exs

`Nx.to_scalar/1` has been renamed to `Nx.to_number/1`

Fix: Nx.to_scalar in examples

---

lib/axon/loop.ex

There is a problem with :io_lib.format in function supervised_log_message_fn/2. If a metric passed to the function is an integer type (like a number of true positive predictions), then :io_lib.format with options '~.5f' won't work correctly. To fix this I propose format_metric/1 which will handle this issue. I found the problem when I ran "credit_card_fraud.exs".

log function improved

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/mixed_precision/policy.ex
test/axon_test.exs
test/compiler_test.exs
test/mixed_precision_test.exs

New model inspection includes memory space and layer policies so you have a better idea of space requirements and types. Example:
```elixir
model =
Axon.input({nil, 784}, name: "input")
|> Axon.dense(128, name: "dense1")
|> Axon.dense(10, name: "dense2")
|> Axon.softmax(name: "softmax")
```
Inspected:
```
--------------------------------------------------------------------------------------------------------------
Model
==============================================================================================================
Layer                             Shape        Policy                         Parameters   Parameters Memory
==============================================================================================================
input ( input )                   {nil, 784} …
```

Improve inspect

---

lib/axon/loop.ex

See each commit for more information.
This allows Axon to compile.  Tests are now working locally.
Fixes: #211

Variable name typo and invalid function arity in Axon.Loop

---

examples/basics/multi_input_example.exs
lib/axon/compiler.ex
test/axon/compiler_test.exs
test/axon/loop_test.exs

Resolves #218 
The initial way to work with multi-input models was to pass a tuple to `Axon.predict` where the order of inputs corresponded to the order inputs we're declared. So if you had a model:
```elixir
x = Axon.input({nil, 1})
y = Axon.input({nil, 1})
z = Axon.input({nil, 1})
model = Axon.add([x, y, z])
```
You would pass values for `x`, `y`, and `z` in order as:
```
Axon.predict(model, params, {x_val, y_val, z_val})
```
Because `x` was declared before `y` was declared before `z`. This was done before Nx supported maps, so it was the easiest way to accomplish multi-inputs. We sort inputs by the Layer's ID because it's a monotonically increasing random integer, and this was the easiest way to ensure inputs we're mapped correctly.
I think now because we support generic containers it …

Allow maps as inputs to predict

---

lib/axon/optimizers.ex
lib/axon/updates.ex

Updates documentation to specify the true default value of `eps_root` used by the Adam optimizer.

Fix Default Value of eps_root in Adam Documentation

---

lib/axon/layers.ex

The layer docs and the top-level API use the word "beta".

Unify argument names in normalization layers

---

.gitignore
lib/axon/loop.ex
test/axon/loop_test.exs

Currently in the `file_pattern` function of `Loop.checkpoint` only epoch and iteration get passed through. This limitation makes it impossible to include metrics like loss in the filename which can be helpful. 
To solve this we can pass the whole loop state to the `file_pattern` function.
With this change we can specify the file_pattern like this.
```elixir
Axon.input({nil, 1})
|> Axon.dense(1)
|> Loop.trainer(:binary_cross_entropy, :sgd, log: 0)
|> Loop.checkpoint(file_pattern: fn state -> "epoch_#{state.epoch}_#{state.metrics["loss"]}.ckpt" end)
|> Loop.run([{Nx.tensor([[1]]), Nx.tensor([[2]])}], epochs: 3)
```
This PR also adds tests for checkpoint.

Make Loop.checkpoint `file_pattern` function more flexible

---

lib/axon.ex
lib/axon/activations.ex
lib/axon/compiler.ex
lib/axon/layers.ex
lib/axon/loop.ex
lib/axon/recurrent.ex
lib/axon/shared.ex
lib/axon/stateful_output.ex
test/axon/compiler_test.exs
test/axon/layers_test.exs
test/axon/mixed_precision_test.exs
test/axon_test.exs

This PR aims to greatly simplify the compiler by tweaking a few things and following a few unifying principles. I think the goal is for this to be the final evolution of the layer API into an interface that is flexible, simple, and easy to understand. Overall here's what needs to happen/change:
1) Parameters need to be defined with `Axon.param` and passed as a list to `layer` in the order they are to be passed to their implementation function. The original usage of map I think was for order preservation/forwarding, but it's actually not necessary and creates some ambiguity about what the name of the parameter being referenced is. I think the list is more clear as the order you give parameters in the list is the order they will be used. Another option even is to just pass everything …

Simplify compiler

---

lib/axon/compiler.ex

This seems to be the tweak that allows EXLA Backend and Compiler to coexist within Axon. I'm still troubleshooting an issue that EXLA raises though about casting types (at least when performing inference on various transformer models)

Explicit backend transfer of constants

---

lib/axon.ex
test/axon_test.exs

It can be useful to see the aggregated information on a model parameters on the inspection. In this PR I have added this functionality in the Axon inspector and adapted related tests.
```elixir
iex> Axon.input({nil, 1}) |> Axon.dense(10) |> Axon.dense(20)
-----------------------------------------------------------------------------------------------
Model
===============================================================================================
Layer                          Shape       Policy              Parameters   Parameters Memory
===============================================================================================
input_0 ( input )              {nil, 1}    p=f32 c=f32 o=f32   0            0 bytes
dense_0 ( dense["input_0"] )   {nil, 10}   p=f32 c=f32 o=f32   20 …
```

Add aggregated parameter info on model inspection

---

lib/axon/metrics.ex

Using compare operators inside `defn` even with `transform` will not work as expected. 
To do that it needs to be inside a separate function.

Fix accuracy calculation logic

---

lib/axon.ex
lib/axon/compiler.ex
test/axon/compiler_test.exs
test/axon_test.exs

For now the only metadata that is used internally is `op` for custom layers, but this could be useful to external libraries as well

Introduce metadata to Axon

---

lib/axon.ex
lib/axon/shape.ex
test/axon/compiler_test.exs
test/axon_test.exs

It's easy to use a wrong option name (`:eps` vs `:epsilon`, `:stride` vs `:strides`), which results in wrong output and is hard to track down. This PR adds `Keyword.validate!` to all functions in the `Axon` module to prevent that.
Also:
* adds missing `:use_bias` in `conv_lstm`
* fixes `:use_bias` handling in `separable_conv2d`, `separable_conv3d`, `lstm` and `gru`
* normalizes the `:axis` option to `concatenate`
* unifies option docs

Validate options in top-level functions

---

lib/axon/loop.ex
lib/axon/optimizers.ex

Default learning rates for each optimizer.
- `adabelief`
- `adagrad`
- `adam`
- `adamw`
- `radam`
- `fromage`
- `lamb`
- `noisy_sgd`
- `rmsprop`
- `sgd`
- `yogi`

Per-optimizer default learning_rate in `Axon.Loop`

---

lib/axon.ex
lib/axon/mixed_precision.ex

Resolves #117 
I added a bunch of additional metadata utilities, since there was no public API for that yet and exposing an API makes it more clear how to manipulate parts of the Axon struct. Additionally, it allows us to validate internally to avoid messed up graphs and things going wrong at execution time

Add graph manipulation and utilities API

---

lib/axon/metrics.ex

This is pretty useful when training multi class classification problems where you're happy with the correct answer being in the top k rather than being the argmax.
See [pytorch ignite](https://pytorch.org/ignite/generated/ignite.metrics.TopKCategoricalAccuracy.html).
Alternatively, it could be implemented as an opt on `Metrics.accuracy` like in [torchmetrics](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html?highlight=top-k#torchmetrics.Accuracy.params.top_k).

add top-k categorical accuracy

---

lib/axon.ex

I didn't fix the deprecation warnings in tests. Sorry! 😁

Deprecate Axon.init

---

lib/axon.ex
lib/axon/layers.ex
lib/axon/shape.ex
test/axon/compiler_test.exs
test/axon_test.exs

Resolves #286 
In all cases except reshape it doesn't make sense to ignore the batch size since it's irrelevant or strange behavior. This compromise is to remove the logic altogether, and expose a documented `:batch` atom in `Axon.reshape` which can be used to fill in the batch size and works well with `:auto`
Before this is merged I need to test with both AxonOnnx and the other lib

Remove ignore_batch in shape layers

---

mix.exs

By default only display-style math is rendered, so we need a custom configuration.

Render inline math in the docs

---

notebooks/generative/mnist_autoencoder_using_kino.livemd

I added an example showing a workflow for how someone might train a model using Livebook and Axon. The two main contributions that I wasn't able to find in the other examples are using `Kino` to visualize the outputs and using Livebook branches so you can stop execution early without losing your model's state.
Would love to know if there's a better way to do anything here! Specifically - is using `Task.start` a good way to create the interactive Livebook cell? And is there a better workflow than using branches?
I was also unsure if this should go in notebooks/, examples/ or guides/

Add an example notebook for training an autoencoder using branches and Kino

---

lib/axon/loop.ex

Fix Axon.Loop.reduce_lr_on_plateau documentation
1. [`Axon.Loop.validate/3`](https://hexdocs.pm/axon/Axon.Loop.html#validate/3) expects the model as the first parameter
2. The accuracy metric is named "accuracy" by default, `validate` reuses the name.

Fix Axon.Loop.reduce_lr_on_plateau documentation

---

lib/axon.ex
lib/axon/layers.ex
test/axon_test.exs

The dropout rate is always expected to be in the range of [0, 1). With these changes, now an exception is raised if this happens, instead of letting it crash with an arithmetic error.
Closes #367

Add exception when dropout is outside expected range

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/initializers.ex
lib/axon/shared.ex
test/axon/initializers_test.exs
test/axon_test.exs
test/support/axon_test_util.ex

Trying to align more with Flax's implementation which does not split keys but rather generates keys from layer meta

Use layer key meta to split keys

---

lib/axon/loop.ex
notebooks/basics/xor.livemd
notebooks/generative/fashionmnist_autoencoder.livemd
notebooks/generative/fashionmnist_vae.livemd
notebooks/generative/mnist_autoencoder_using_kino.livemd
notebooks/structured/credit_card_fraud.livemd
notebooks/text/lstm_generation.livemd
notebooks/vision/horses_or_humans.livemd
notebooks/vision/mnist.livemd

I updated the notebooks as I was running into issues between the latest version of axon and what was pinned in the notebooks.
Few items:
- Pinned axon to the latest version `0.3.0`
- Updated and pinned any dependencies
- Fixed any bugs caused by the dependency updates
Dev setup:
Livebook v0.7.2
Elixir 1.14.0-OTP-25
MacOS Ventura 13.0 M1
I hope this is useful!

Update notebook dependencies

---

test/axon/integration_test.exs
test/support/axon_test_util.ex
test/test_helper.exs

The focus of the next Axon release is training API. In order to verify the training API is working as expected, we need to actually train models. This introduces some integration tests into the test suite modeled after: https://github.com/keras-team/keras/blob/master/keras/tests/integration_test.py
I also would like to add tests of training real-world models on dummy datasets and compare results with fixed seeds to other frameworks, to ensure we aren't too divergent

Start an integration test suite

---

lib/axon/loop.ex
test/axon/loop_test.exs

Unify event handlers in loops

---

lib/axon/compiler.ex
test/axon/compiler_test.exs

We originally generated a keys map based on layer names, but there are some differences in how we generated layer names between keys and layers. This fixes by using the IDs. The keys map is internal anyway, and IDs are guaranteed to be unique.

Fix issue with initialization missing keys for some layers

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/layers.ex
lib/axon/parameter.ex
test/axon/compiler_test.exs
test/axon/layers_test.exs

Resolves #423 
The integration tests are failing because of a mismatched while-body, and I'm not sure where/how that's happening

Use a layer state to manage dropout state so it changes between runs

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/layers.ex
lib/axon/loss_scale.ex
lib/axon/losses.ex
lib/axon/node.ex
lib/axon/parameter.ex
test/axon/compiler_test.exs
test/axon/loop_test.exs

* Parameter IDs were removed
* Dropouts are completely removed from the network via a new :mode option
* Freezing traverse the nodes directly without relying on IDs
* Removed almost all usage of backend_copy(Nx.Defn.Expr)
* We use integers as cache keys after the cache is built

Provide deterministic builds

---

lib/axon/loop.ex

WDYT @cigrainger? This will avoid conflicts in the future if we ever start using another plotting library and removes any ambiguity.

Use a more assertive name on plotting

---

lib/axon.ex
lib/axon/compiler.ex
test/axon/compiler_test.exs

The previous implementation of dropout would crash
when its child node was accessed directly in the graph.

Implement dropout as a passthrough

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/loop.ex

Also changed Axon.build/2 to require a `:seed`
to normalize with other Axon APIs.

Only compute random key on init

---

lib/axon/compiler.ex

This PR fixes the duplicate wording in an error message in `get_input/3` from the `Axon.Compiler` module.

Remove extra usage of 'expected input' from error message in get_input/3

---

examples/generative/text_generator.exs

This PR resolves an incompatibility conflict amongst the dependencies in the text generator example. I think we should prevent this in the future by setting each dependency to a specific version. This PR also fixes breaking changes resulting from the updated dependencies.
Summary of changes:
- Update dependencies to latest versions
- Update output sequence to first element of tuple returned by `Axon.lstm/2`
- Update deprecated `Nx` function `to_batched_list/3` to `to_batched/3`

Fix text generator example

---

lib/axon.ex

Add paragraph on integrating with Nx.Serving

---

guides/guides.md

The guides readme links were broken.  This PR updates the links to the livemd version and include the correct folder its contained in.

Include the folder for the guide links

---

lib/axon/display.ex

Change `ax_table/2` to `as_table/2`

Fix typo in `Axon.Display.as_table`

---

examples/generative/fashionmnist_autoencoder.exs

The Fashion MNIST autoencoder example throws the same error as the examples in #437. This PR fixes the autoencoder by updating the dependencies and fixing breaking changes.
Summary of changes:
- Update dependencies to latest versions
- Add `:batch` placeholder for dynamic batch size
- Update deprecated `Nx` function `to_batched_list/3` to `to_batched/3`
- Use `Enum.fetch!/2` since `hd/1` does not work on a stream
- Remove unused alias for `Axon.Loop.State`
- Fix spelling of MNIST in module name

Fix Fashion MNIST autoencoder example

---

lib/axon/activations.ex
lib/axon/compiler.ex
lib/axon/initializers.ex
lib/axon/layers.ex
lib/axon/schedules.ex
lib/axon/shared.ex

Cleaning up final blockers before next release

Fix deprecation warnings with new Nx

---

guides/training_and_evaluation/writing_custom_event_handlers.livemd
lib/axon/loop.ex

Goes along with streaming. The differentiator is to possibly implement some mechanism for 2 way communication with a loop running async

Deprecate Axon.Loop.handle/4

---

lib/axon/layers.ex

Hey 👋 
I'm opening this small PR to fix a discrepancy in the docs for the option `channels` used in the Conv layers and others.
The default value for the `:channels` option is `:last` based on what I can see in the code (e.g. [here](https://github.com/elixir-nx/axon/blob/7c21ae75d34e68c946a8ff24a46f194f9d17003a/lib/axon/layers.ex#L356)).
Note that in the `Axon` module docs, the default value for the option is correct, only in the `Axon.Layers` it was outdated/incorrect (`:first`).
Cheers ✌️

docs: update `channels` default value mentioned in the docs

---

lib/axon.ex

The following code from the [model hooks](https://hexdocs.pm/axon/model_hooks.html) guide should call `IO.inspect` for both `hook1` and `hook2`. Instead it only runs `hook2`.
```elixir
model =
Axon.input("data")
|> Axon.dense(8)
|> Axon.attach_hook(fn val -> IO.inspect(val, label: :hook1) end, on: :forward)
|> Axon.attach_hook(fn val -> IO.inspect(val, label: :hook2) end, on: :forward)
|> Axon.relu()
{init_fn, predict_fn} = Axon.build(model)
params = init_fn.(input, %{})
predict_fn.(params, input)
```
`Axon.attach_hook` should accumulate hooks instead of overwriting the `node.hooks` variable with the most recent hook.

Fix support for multiple hooks in `attach_hook`

---

lib/axon/compiler.ex
lib/axon/mixed_precision.ex
lib/axon/mixed_precision/policy.ex
test/axon/integration_test.exs
test/axon/mixed_precision_test.exs

Resolves #496 
When a user has a pretrained model with some initialized state, we do not cast that state to the model's desired policy if they try to use mixed precision. This fixes that.
It kind of makes me think though that maybe we should rethink mixed precision a bit? I'm not exactly sure how, but doing this implicitly feels weird to me. Maybe the alternative is to recommend the parameters in this case be cast to the desired type explicitly.

Fix precision issue

---

lib/axon/loop.ex

The trainer function is currently looking for :loss_cale in opts. This should pick out the right options and pass them to train_step

fix loss_scale atom typo in Axon.Loop.trainer

---

examples/vision/horses_or_humans.exs

- channels transpose no longer needed (it seems?)
- Polaris references in example needs polaris dependency until next axon is released
- Fix erroneous png parsing
- Updates dataset source URL

Fixes horses_or_humans.exs example

---

test/axon/compiler_test.exs

These are green for Nx.BinaryBackend, but failing for exla and torchx because of tensor native refs being different on equality.

test: fixes Axon.block tests

---

lib/axon/compiler.ex
lib/axon/layers.ex
test/axon/compiler_test.exs

Resolves #544
Also resolves #545 (we just don't wrap those layers with metadata)
Also resolves #464 
The issue in 544 was that we were casting embedding layer integer inputs to f16, and then casting back to s64 which causes all sorts of issues because of loss of precision. Now we just never cast integer types at all. We get the same outputs now with f16:
```
%{
results: [
%{
text: "[INST] <<SYS>>\nYou are a bot.\n<</SYS>>\n\nHi, bot![/INST]  Hello! *chirp* *winking emoji* I'm so glad you said hi to me! I'm just an AI bot, here to help answer your questions and provide some fun and interesting responses. What's on your mind? 🤖"
}
]
}
```

Do not cast integer to float unintentionally

---

notebooks/vision/horses_or_humans.livemd

- Update to latest stable dependencies to fix issue of `Polaris.Optimizers` module not available.
- Update code examples to newer dependency APIs.
- Update URL of moved resource (the dataset).
Dataset reference: https://laurencemoroney.com/datasets.html#horses-or-humans-dataset

Update "Horses or humans" example.

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/layers.ex
lib/axon/loop.ex
lib/axon/parameter.ex
test/axon/compiler_test.exs
test/axon/integration_test.exs
test/axon/layers_test.exs
test/support/axon_test_util.ex

RNNs with while loops are still messed up, but this introduces composite parameters which will be used in LoRA and fixes #530

Introduce composite params, fix stability issue with unrolled RNNs

---

lib/axon.ex
lib/axon/layers.ex
test/axon/layers_test.exs

Same as https://github.com/elixir-nx/nx_image/pull/5.

Add option to control anti-aliasing in the resize layer

---

lib/axon/loop.ex
test/axon/loop_test.exs

If multiple event handlers are registered for the same event, the counter is incremented before each handler. This results in filters like `every: 10` to never match any events.

Fix event count for multiple handlers

---

lib/axon/compiler.ex
lib/axon/mixed_precision.ex

Unifies the policy casting behaviour between the compiler and an explicit cast.

Do not cast integers in in Axon.MixedPrecision.cast/2

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/node.ex
test/axon/compiler_test.exs

This allows to configure model layers at Axon-compilation time. This is useful if we want to make some compilation-time decisions when calling the model, without building a different model altogether.
API-wise the options are passed as
```elixir
Axon.build(model, global_layer_options: [output_hidden_states: true])
```
Those options are merged into layer options, but only when declared explicitly, like so:
```elixir
Axon.layer(
fn hidden_state,  opts ->
if opts[:output_hidden_states] do
...
else
...
end
end,
[input],
global_options: [:output_hidden_states]
)
```
We could pass them nested too and access as `opts[:global_options][:output_hidden_states]`, but this would break all existing layers that have options allowlist using `keyword!`. I actually think that merging them in a flat manner …

Add support for global layer options

---

lib/axon.ex
lib/axon/layers.ex
lib/axon/loop.ex
lib/axon/metrics.ex

Some sections of the documentation are displaying incorrectly in ExDoc
cc: @josevalim @jonatanklosko @seanmor5 
before:
after:

improved doc formatting by fixing indentation and escape characters

---

lib/axon/loop.ex

Currently it says:
`checkpoint_{epoch}.ckpt` (which indicates that this is the default)
But below it is correctly documented as:
`checkpoint_{epoch}_{iteration}.ckpt` (which is the correct default)
Thank you for reviewing!

Fix docs file basename

---

examples/vision/mnist.exs
lib/axon.ex
lib/axon/compiler.ex
lib/axon/loop.ex
lib/axon/loss_scale.ex
lib/axon/model_state.ex
lib/axon/parameter.ex
test/axon/compiler_test.exs
test/axon/integration_test.exs
test/axon/loop_test.exs
test/axon_test.exs
test/support/axon_test_util.ex

cc @jonatanklosko @josevalim 
Almost all tests passing, have to rebase as well

Use model state struct instead of parameters

---

lib/axon.ex
lib/axon/node.ex

Resolves #549 
Rather than allow overriding those internal, we instead add a `:meta` property which can be used to add metadata to nodes for other libraries to use. All of the built-ins support this metadata

Add meta property to nodes

---

lib/axon.ex
lib/axon/compiler.ex
test/axon/compiler_test.exs

Support blocks with multiple inputs

---

lib/axon.ex
lib/axon/compiler.ex
lib/axon/mixed_precision.ex
lib/axon/mixed_precision/policy.ex
lib/axon/parameter.ex
mix.exs
test/axon/compiler_test.exs

Rather than requiring shape/type we can just use templates. The benefit is that this work supports using any Nx.Container as a model parameter. For right now we still support the old style under the `param` function, but this defers to the new `parameter` which requires templates.
There are certain places where using a container/composite parameter in place of a regular parameter makes sense. For example, if we want to initialize quantized models then we can create a quantized tensor container which represents a quantized parameter that can be converted back to a regular parameter.
In the future, I plan to unify the currently separated shape calculation and initialization process for a parameter. Realistically each parameter should just take input templates, do the shape calculation, and …

Use templates as parameters

---

lib/axon.ex
test/axon/compiler_test.exs

Resolves #529. This is a proper node rewriting API that should be much more flexible and easier than the `wrap_nodes` proposed earlier. Now LoRA can be implemented like this:
```elixir
lora_dense_rewriter = fn [%Axon{} = x], %Axon{} = wx ->
x
|> Axon.dropout(rate: 0.1)
|> Axon.dense(units_a, use_bias: false, name: "lora_a")
|> Axon.dense(units_b, use_bias: false, name: "lora_b")
|> Axon.multiply(scaling)
|> Axon.add(wx)
end
lora_model = Axon.rewrite_nodes(model, fn
%Axon.Node{op: :dense} -> lora_dense_rewriter
_ -> :skip
end)
```
It also supports more complex rewriters. I will continue expanding this API until we have something closer to `torch.fx`

Add rewrite_nodes function

---

CHANGELOG.md

Hi,
I wanted to check the CHANGELOG.md but I saw it was not updated.
Using https://diff.hex.pm/diff/axon/0.5.1..0.6.0 I made a quick summary between those versions.
Thank you for reviewing.

Update changelog with changes between v0.5.1..v0.6.0

---

lib/axon/quantization.ex
test/axon/quantization_test.exs

Fix: call apply/3 as intended

---

lib/axon/compiler.ex
test/axon/compiler_test.exs
test/axon/loop_test.exs

Raise on ambiguous inputs

---

lib/axon.ex

Tiny doc fix - the `tanh_rewriter` example was using `relu` instead of `tanh`

Doc fix for `rewrite_nodes`

---

lib/axon/display.ex

Fixes https://github.com/elixir-nx/axon/issues/604 and multi inputs model, see example below:
```elixir
[Axon.input("input_1"), Axon.input("input_2")]
|> Axon.concatenate()
|> Axon.dense(32, activation: :relu)
|> Axon.dropout(rate: 0.5)
|> Axon.dense(1)
|> Axon.Display.as_table(%{"input_1" => Nx.iota({2, 1}), "input_2" => Nx.iota({2, 2})})
```
Expected output
```shell
+------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                  Model                                                                   |
+===============================+============================================+======================+=================+====================+
| …
```

Handle Model Display Correctly
